name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy React app to GitHub Pages
        run: |
          cd front
          npm install
          npm run build
          mv dist depl
          git fetch
          git checkout gh-pages
          git add depl
          git config --global user.email "cd5e@pm.me"
          git config --global user.name "bot-coldase"
          git commit -m "Update pages"
          git push origin gh-pages
