name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: front

    steps:
      - uses: actions/checkout@v3

      - run: |
          npm i
          npm ci
          npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com       
          git --work-tree dist add --all
          git commit -m "Automatic Build and Deploy run by GitHub Actions"
          git push origin HEAD:gh-pages --force
