name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy React app to GitHub Pages
        run: |
          cd front
          npm install
          npm run build
          git checkout gh-pages
          git add dist/
          git commit -m "Update build"
          git push origin gh-pages
