name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          git config --global user.email "cd5e@pm.me"
          git config --global user.name "coldase-bot"
          git remote set-url origin https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USER }}/${{ secrets.GH_REPO }}
          npm install
          npm run deploy
