name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v3

      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: Build and deploy
        run: |
          npm install
          npm run deploy
