name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          git remote set-url origin https://coldase:${{ secrets.GH_TOKEN }}@github.com/coldase/project-x
          npm install
          npm run deploy
